"""
This type stub file was generated by pyright.
"""

from .snappy import HadoopStreamCompressor, HadoopStreamDecompressor, StreamCompressor, StreamDecompressor, UncompressError, compress, decompress, isValidCompressed, stream_compress, stream_decompress, uncompress

__version__ = ...
