"""
This type stub file was generated by pyright.
"""

def cmdline_main(): # -> None:
    """This method is what is run when invoking snappy via the commandline.
    Try python -m snappy --help
    """
    ...

if __name__ == "__main__":
    ...
