"""
This type stub file was generated by pyright.
"""

"""Consts and function to handle target format.
ALL_SUPPORTED_FORMATS - list of supported formats
get_decompress_function - returns stream decompress function for a current
    format (specified or autodetected)
get_compress_function - returns compress function for a current format
    (specified or default)
"""
DEFAULT_FORMAT = ...
ALL_SUPPORTED_FORMATS = ...
_COMPRESS_METHODS = ...
_DECOMPRESS_METHODS = ...
_DEFAULT_COMPRESS_FORMAT = ...
def uvarint(fin):
    """Read uint64 nbumber from varint encoding in a stream"""
    ...

def check_unframed_format(fin, reset=...): # -> bool:
    """Can this be read using the raw codec

    This function wil return True for all snappy raw streams, but
    True does not mean that we can necessarily decode the stream.
    """
    ...

_DECOMPRESS_FORMAT_FUNCS = ...
def guess_format_by_header(fin): # -> tuple[Literal['framed', 'hadoop', 'raw'], Any]:
    """Tries to guess a compression format for the given input file by it's
    header.

    :return: format name (str), stream decompress function (callable)
    """
    ...

def get_decompress_function(specified_format, fin):
    ...

def get_compress_function(specified_format):
    ...

