name: Build Wheels
on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install cibuildwheel
        run: pip install cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
      - name: Build sdist
        run: python -m build --sdist --outdir dist
      - uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*.whl
